import { CreditedImage } from "../components/Credited";
import { NODE_BOM, NODE_BOM_TOTAL_CAD } from "../data/bom";

export function Hardware() {
  return (
    <>
      <section className="section" style={{ paddingTop: 48 }}>
        <div className="container">
          <div className="eyebrow">Hardware</div>
          <h1>One node design, three RF bands, a receive-only mesh.</h1>
          <p style={{ maxWidth: 720 }}>
            Every node is electrically identical: one wideband transceiver (70 MHz–6 GHz), three
            band-specific antenna/filter front ends, GNSS-disciplined timing, and Gigabit PoE
            backhaul that doubles as a 5–6 GHz sensing link. What differs node to node is only the
            antenna aiming and mount — the fabrication scripts in{" "}
            <code>hardware/antennas/</code> and <code>hardware/mech/</code> parametrize that.
          </p>
        </div>
      </section>

      <section className="section">
        <div className="container grid grid-2" style={{ alignItems: "center" }}>
          <CreditedImage id="sdr-hackrf-pcb" alt="A software-defined radio board, representative of the wideband transceiver class used in the node" />
          <div>
            <h2>What "fabrication-ready" means here</h2>
            <p>
              Antenna geometry, the enclosure, the mounting bracket, and the interceptor airframe
              are generated by scripts that emit real fabrication files — antenna dimensions plus a
              build sheet, and STL/3MF solids for anything 3D-printed or CNC'd
              (<code>hardware/antennas/</code>, <code>hardware/mech/</code>,{" "}
              <code>hardware/interceptor/</code>).
            </p>
            <div className="callout" style={{ marginTop: 12 }}>
              <p>
                <strong>The RF/timing carrier board is not.</strong> It ships as a complete KiCad
                schematic, netlist, and component placement with a checked BOM
                (<code>hardware/pcb/</code>) — but routing and DRC sign-off on a board mixing a
                6 GHz RF front end, GNSS, and an OCXO is a licensed PCB/RF engineer's task, not
                something a script should claim to have done. Overclaiming "manufacture-ready" on
                an unrouted RF board is exactly the kind of shortcut that costs credibility at the
                first supplier call.
              </p>
            </div>
          </div>
        </div>
      </section>

      <section className="section">
        <div className="container">
          <div className="eyebrow">Bill of materials</div>
          <h2>
            Per-node cost: <span className="mono" style={{ color: "var(--accent)" }}>CAD {NODE_BOM_TOTAL_CAD.toFixed(2)}</span>
          </h2>
          <p style={{ maxWidth: 720 }}>
            Distributor list pricing at ~50-unit quantity, September 2026. See{" "}
            <code>hardware/bom/node_bom.csv</code> for the machine-readable version and{" "}
            <code>hardware/bom/README.md</code> for sourcing notes, FX exposure, and the Canadian
            supply-chain assessment.
          </p>
          <div style={{ overflowX: "auto" }}>
            <table>
              <thead>
                <tr><th>Ref</th><th>Part</th><th>Function</th><th>Qty</th><th>Unit (CAD)</th><th>Ext. (CAD)</th></tr>
              </thead>
              <tbody>
                {NODE_BOM.map((l) => (
                  <tr key={l.ref}>
                    <td className="mono">{l.ref}</td>
                    <td>{l.part}<div style={{ fontSize: "0.75rem", color: "var(--text-faint)" }}>{l.mpn}</div></td>
                    <td style={{ fontSize: "0.85rem" }}>{l.function}</td>
                    <td className="mono">{l.qty}</td>
                    <td className="mono">{l.unitCostCad.toFixed(2)}</td>
                    <td className="mono">{(l.qty * l.unitCostCad).toFixed(2)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </section>

      <section className="section" style={{ borderBottom: "none" }}>
        <div className="container">
          <div className="eyebrow">Roadmap item — not a Sandbox 2027 deliverable</div>
          <h2>Penumbra Talon: track-cued net-capture interceptor</h2>
          <p style={{ maxWidth: 720 }}>
            Costed and simulated (<code>penumbra/sim/intercept.py</code>) as a future defeat-layer
            concept, cited to the same reasoning as Tornyol-class interceptors: a net + drag
            parachute is the only effector family with a controlled descent over a populated area.
            The applicant guide for the urban sandbox explicitly does not permit demonstrating a
            defeat mechanism there, so Talon is designed and priced for the roadmap, not flown at
            the event.
          </p>
          <div className="grid grid-3" style={{ marginTop: 16 }}>
            <div className="panel">
              <div className="stat"><div className="value">30+ m/s</div><div className="label">Interceptor speed</div></div>
            </div>
            <div className="panel">
              <div className="stat"><div className="value">~9 g</div><div className="label">Turn authority</div></div>
            </div>
            <div className="panel">
              <div className="stat"><div className="value">Net + parachute</div><div className="label">Effector, controlled descent</div></div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
