import { Link } from "react-router-dom";
import { CreditedImage } from "../components/Credited";

const DIFFERENTIATION = [
  {
    modality: "Radar",
    observable: "Direct RF return from the target",
    limitation: "Clutter, multipath, and small-target sensitivity in urban/contested conditions",
  },
  {
    modality: "RF emission detection",
    observable: "Transmissions generated by the UAS itself",
    limitation: "Useless against RF-silent or fully autonomous systems",
  },
  {
    modality: "Optical / EO-IR",
    observable: "Visual appearance of the target",
    limitation: "Line-of-sight, occlusion, weather and lighting dependent",
  },
  {
    modality: "Acoustic",
    observable: "Rotor / airframe sound",
    limitation: "Urban background noise, wind, and distance destroy SNR quickly",
  },
];

export function Home() {
  return (
    <>
      <section className="section" style={{ paddingTop: 64 }}>
        <div className="container">
          <div className="eyebrow">Technical concept · detection &amp; tracking only</div>
          <h1 style={{ maxWidth: 780 }}>
            A passive, multistatic RF mesh that turns broadcast towers and cell sectors already
            lighting up the city into a counter-UAS radar.
          </h1>
          <p style={{ maxWidth: 640, fontSize: "1.05rem" }}>
            PENUMBRA does not transmit. It listens for the way a small aircraft perturbs signals
            that ATSC television, LTE/5G, and the mesh's own Wi-Fi backhaul are already sending
            across a city — then uses coherent cross-ambiguity processing, the same class of
            technique used in passive coherent radar, to recover range, Doppler, and a track.
          </p>
          <div style={{ display: "flex", gap: 12, flexWrap: "wrap", marginTop: 28 }}>
            <Link to="/simulator" className="btn primary">Run the link-budget simulator →</Link>
            <Link to="/architecture" className="btn">How the sensing works</Link>
          </div>
        </div>
      </section>

      <section className="section">
        <div className="container grid grid-2" style={{ alignItems: "center" }}>
          <div>
            <div className="eyebrow">Core proposition</div>
            <h2>Illuminate with what's already on air. Listen everywhere at once.</h2>
            <p>
              Conventional counter-UAS radar has to build and protect its own transmitter. PENUMBRA's
              nodes are receive-only: they exploit ATSC broadcast television, LTE/5G downlink, and the
              mesh's own Wi-Fi links as "illuminators of opportunity," and recover a target's bistatic
              range and Doppler by cross-correlating a reference channel against a surveillance channel —
              the same coherent-processing-gain argument used in passive covert radar (Griffiths &amp; Baker,
              2017), adapted to Canadian ATSC broadcast (not the DVB-T signal most passive-radar papers
              assume) and to a distributed, disposable mesh rather than one large fixed site.
            </p>
            <p>
              Because every node is receive-only, the mesh emits nothing to jam, direction-find, or
              regulate under a transmit licence, and a lost or destroyed node degrades coverage locally
              rather than taking the system down.
            </p>
          </div>
          <CreditedImage id="uhf-vhf-antenna" alt="UHF/VHF television broadcast antenna on a rooftop mast" />
        </div>
      </section>

      <section className="section">
        <div className="container">
          <div className="eyebrow">Why urban detection is hard</div>
          <h2>Every incumbent modality loses something in the city PENUMBRA is built for.</h2>
          <div className="grid grid-2" style={{ marginTop: 24, alignItems: "start" }}>
            <table>
              <thead>
                <tr><th>Modality</th><th>Primary observable</th><th>Urban limitation</th></tr>
              </thead>
              <tbody>
                {DIFFERENTIATION.map((d) => (
                  <tr key={d.modality}>
                    <td><strong>{d.modality}</strong></td>
                    <td>{d.observable}</td>
                    <td>{d.limitation}</td>
                  </tr>
                ))}
              </tbody>
            </table>
            <div className="panel">
              <h3 style={{ marginTop: 0 }}>PENUMBRA's distinction</h3>
              <p style={{ marginBottom: 12 }}>
                Independent physical observable: coherent multistatic reflections of ambient
                transmissions the target does not control and cannot silence. No dependence on the
                UAS emitting anything. Non-imaging, so it keeps working below rooftops, at night,
                and in weather that degrades EO/IR.
              </p>
              <p style={{ marginBottom: 0 }}>
                It is explicitly a <strong>complementary layer</strong>, not a replacement — see the{" "}
                <Link to="/program">honest novelty statement</Link> and the competitive positioning
                in the program plan.
              </p>
            </div>
          </div>
        </div>
      </section>

      <section className="section" style={{ borderBottom: "none" }}>
        <div className="container grid grid-2" style={{ alignItems: "center" }}>
          <CreditedImage id="ottawa-skyline" alt="Downtown Ottawa skyline, a representative dense-urban CUAS deployment environment" />
          <div>
            <div className="eyebrow">Non-goals</div>
            <h2>What this program does not claim.</h2>
            <ul style={{ color: "var(--text-dim)", paddingLeft: 20 }}>
              <li>No autonomous engagement or defeat mechanism is part of the detection system.</li>
              <li>No person-identification capability is required or built.</li>
              <li>No assumption that PENUMBRA replaces radar, optical, acoustic, or RF-emission sensing.</li>
              <li>No claim that the concept is proven until physics and field experiments validate it — see the <Link to="/program">stage-gate program</Link>.</li>
            </ul>
            <p className="callout" style={{ marginTop: 16 }}>
              A net-capture interceptor concept exists as a costed future-roadmap item (see{" "}
              <Link to="/hardware">Hardware</Link>) but is <strong>not</strong> part of any Sandbox
              demonstration — the applicant guide does not permit demonstrating a defeat mechanism
              in the urban sandbox.
            </p>
          </div>
        </div>
      </section>
    </>
  );
}
